export const iconSlugs = [
  "typescript",
  "javascript",
  "react",
  "nodedotjs",
  "express",
  "nextdotjs",
  "git",
  "github",
  "java",
  "c",
  "python",
  "django",
  "fastapi",
  "postgresql",
  "mongodb",
  "reactquery",
  "tailwindcss",
  "redux",
  "tensorflow",
  "docker",
  "redis",
  "rabbitmq",
  "sqlite",
  "kubernetes",
  "linux",
  "storybook",
];

export default {
  name: "Kislev Levy",
  role: "Full Stack Developer",
  phone: "972526171300",
  email: "kislev.levy@gmail.com",
  links: {
    github: "https://github.com/kislevlevy",
    linkedin: "https://www.linkedin.com/in/kislevlevy",
    website: "https://portfolio.kislev.dev/",
  },
};
