export default {
  name: "Kislev Levy",
  role: "Full Stack Developer",
  phone: "972526171300",
  email: "kislev.levy@gmail.com",
  links: {
    github: "https://github.com/kislevlevy",
    linkedin: "https://www.linkedin.com/in/kislevlevy/",
    website: "https://kislev.me/",
  },

  slugs: [
    "typescript",
    "javascript",
    "react",
    "html5",
    "css3",
    "nodedotjs",
    "express",
    "nextdotjs",
    "prisma",
    "firebase",
    "vercel",
    "git",
    "github",
    "visualstudiocode",
    "adobecreativecloud",
    "bootstrap",
    "tailwindcss",
    "redux",
    "npm",
    "json",
    "cloudinary",
    "mongodb",
    "mongoose",
    "pug",
    "jquery",
    "tensorflow",
    "vite",
    "render",
    "mui",
    "shadcnui",
    "axios",
    "jsonwebtokens",
    "paypal",
    "hostinger",
  ],
};
